### ISSUE TITLE
Support for October CMS v3

### ISSUE THREAD

**Issue by artistro08** [mplodowski/seomanager-plugin-public#28]
I would love support for October v3. I would like for you to support Tailor structures and streams.

The current alternative would be to build the structures myself but I would like it to just "work" when a page is a structure or stream

**Comment by mplodowski** [comment]
Hi,

please upgrade to plugin version 4.0. I added October CMS Tailor support.

Plugin adds two mixins with Meta and Open Graph fields to Tailor. You just need to add them to your blueprint Entry
in `fields` section like so:

```
_seo_meta_fields:
    type: mixin
    source: Renatio\SeoManager\MetaFields

_seo_og_fields:
    type: mixin
    source: Renatio\SeoManager\OgFields
```

After that remember to save and migrate blueprint or run `php artisan october:migrate` command.

I tested this with example Blog, Author, Category, Wiki Article entries provided in demo theme.
